site_name: grupo1

repo_name: '2024.2-Bluesky'
repo_url: https://github.com/Requisitos-de-Software/2024.2-Bluesky
# site_url: 
edit_uri: edit/main/docs/

# copyright: Copyright & copy; 2024 Nome do app

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js


theme:
  custom_dir: overrides
  name: material
  language: pt-BR
  logo: /assets/images/Bluesky_app_icon.png
  favicon: /assets/images/icon.svg

  icon:
    repo: fontawesome/brands/github

  features:
    - toc.integrate
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.instant
    - navigation.top

  hide: 
    - 
    
  extra:
    social:
      - icon: fontawesome/brands/mastodon
        link: https://fosstodon.org/@squidfunk
    
  plugins: 
    - search:
        lang: pt-BR

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: custom-icons/contrast-light
        name: Modo Claro
    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: custom-icons/contrast-dark
        name: Modo Escuro

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons 
  - footnotes 

nav:
  - Home: Home/index.md
  - Atas:
    - 1º reuniao: Atas/reuniao_1.md
    - 2º reuniao: Atas/reuniao_2.md
    - 3º reuniao: Atas/reuniao_3.md
  - Apresentações: 
    - Apresentação 1: Home/apresentacao1.md
    - Apresentação 2: Home/apresentacao2.md
    - Apresentação 3: Home/apresentacao3.md
  - Cronograma Executado: Home/cronogramaex.md

  - Desenvolvimento:
    - Cronograma Planejado: Desenvolvimento/cronograma.md
    - Disponibilidade dos Integrantes: Desenvolvimento/disponibilidade.md
    - Ferramentas: Desenvolvimento/ferramentas.md
    - Apps Avaliados: Desenvolvimento/apps_avaliados.md
    - App Escolhido: Desenvolvimento/app_escolhido.md

  - Elicitação de Requisitos:
    - Questionário Perfil do Usuário: PerfilUsuario/PerfilUser.md
    - Resultado Perfil do Usuário: PerfilUsuario/Resultado.md
    - Personas: PerfilUsuario/Personas.md

    - Técnicas de Elicitação:
      - Questionário Elicitação: PerfilUsuario/Tecnicas/Questionario.md
      - Observação: PerfilUsuario/Tecnicas/Observacao.md
      - Introspecção: PerfilUsuario/Tecnicas/Introspeccao.md
      - Brainstorm: PerfilUsuario/Tecnicas/Brainstorm.md
      - Requisitos Elicitados: PerfilUsuario/Tecnicas/Requisitosel.md
    - Tecnicas de Priorização:
      - Three Level Scale: PerfilUsuario/TecnicasPrior/Three.md
      - First Things First: PerfilUsuario/TecnicasPrior/FirstThingsFirst.md
      - $100: PerfilUsuario/TecnicasPrior/100.md

  - Modelagem: 
    - Cenários: Modelagem/Cenario.md
    - Léxicos: Modelagem/Lexicos.md
    - Casos de Uso: Modelagem/Caso_de_uso.md
    - Especificação Suplementar: Modelagem/Especificacao.md

  - Inspeção: 
    - Etapa 1:
      - Planejamento Etapa 1: Revisao/Etapa1/planejamento1.md
      - Inspeção etapa 1: Revisao/Etapa1/revisãoGrupo.md
      - Rich Pictures do grupo: Revisao/Etapa1/RichPicturesGrupo.md
      - Inspesão grupo 02: Revisao/Etapa1/Inspesao02.md
    - Etapa 2:
      - Planejamento Etapa 2: Revisao/Etapa2/planejamento.md
      - Inspeção etapa 2: Revisao/Etapa2/resultado.md
      - Inspeção grupo 02: Revisao/Etapa2/Inspesao02.md
    - Etapa 3:
      - Planejamento Etapa 3: Revisao/Etapa3/planejamento.md
      - Inspeção etapa 3: Revisao/Etapa3/resultado.md
      - Inspeção cenários: Revisao/Etapa3/cenarios.md
      - Inspeção grupo 02: Revisao/Etapa3/Inspesao03.md

